name: parsec_windows
description: Windows implementation of the parsec plugin.
version: 0.1.0
repository: https://github.com/oxeanbits/parsec_flutter/tree/main/parsec_windows

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  parsec_platform_interface: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    implements: parsec
    platforms:
      windows:
        pluginClass: ParsecWindowsPluginCApi
        dartPluginClass: ParsecWindows
