name: parsec
description: Multi-platform `parsec` plugin for Flutter to calculate math equations using C++ library. Supports android.
version: 0.3.0
repository: https://github.com/oxeanbits/parsec_flutter/tree/main/parsec

environment:
  sdk: ">=2.18.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  parsec_platform_interface: ^0.1.1
  parsec_android: ^0.3.0
  parsec_linux: ^0.3.0
  parsec_windows: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        default_package: parsec_android
      linux:
        default_package: parsec_linux
      windows:
        default_package: parsec_windows
